name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
      with:
        path: flexible-use-cases
    - name: Checkout flexible-core
      uses: actions/checkout@v4
      with:
        repository: ftacchini/flexible-core
        path: flexible-core
    - name: Checkout flexible-decorators
      uses: actions/checkout@v4
      with:
        repository: ftacchini/flexible-decorators
        path: flexible-decorators
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install and build flexible-core
      working-directory: flexible-core
      run: |
        npm install
        npm run build
    - name: Install and build flexible-decorators
      working-directory: flexible-decorators
      run: |
        npm install ../flexible-core
        npm install
        npm run build
    - name: Install, build, and test flexible-use-cases
      working-directory: flexible-use-cases
      run: |
        npm install ../flexible-core
        npm install ../flexible-decorators
        npm install
        npm run build --if-present
        npm run test
      env:
        CI: true
